### ISSUE TITLE
Feature request: Support changing starter module in the bootstrap

### ISSUE THREAD

**Issue by andrew-flatters-bliss** [Azure/alz-terraform-accelerator#106]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.7.3 on windows_amd64

**azure provider**: 

**module**:  1.1.6

![image](https://github.com/Azure/alz-terraform-accelerator/assets/63094835/5fd8ffc9-b886-4224-bdcb-9417855cf9df)

### Description

Ran though  `New-ALZEnvironment -i "terraform" -c "azuredevops"` selected the staarter_module been `basic` the first time, but then realised to add the networking we'd need that. So running `hubnetworking` the second time around via the accelerator seemed to do the correct changes although I noticed that the module gets renamed which caused a destroy of everything that was already setup via basic and redoes its work. 

GIT Diff:

-module "enterprise-scale" {
+module "enterprise_scale" {

* Run `New-ALZEnvironment -i "terraform" -c "azuredevops"` and use starter_module `basic`
* Ran the resulting DevOps pipelines to get rest of bootstrapping done
*  Run `New-ALZEnvironment -i "terraform" -c "azuredevops"` and use starter_module `hubnetworking`
* Run validate and see output looks incorrect
* Result `Plan: 258 to add, 0 to change, 247 to destroy.`

![image](https://github.com/Azure/alz-terraform-accelerator/assets/63094835/a9f6a3a0-e60d-415d-b32c-ce080208f9d1)

**Comment by jaredfholgate** [comment]
Hi @andrew-flatters-bliss. Thanks for reporting this. This is not a scenario we have tested, but theoretically it should be possible, so will take a look and figure out why it is doing this and report back.

**Comment by andrew-flatters-bliss** [comment]
Cheers @jaredfholgate, also great talk on Wednesday just got around to checking it out today.  👍

**Comment by jaredfholgate** [comment]
I tried to replicate this, but have been unable to. I used an inputs config file to ensure I only changed the starter module and nothing else, but works exactly the same as if I had supplied the variables via the prompts.

1. Deploy `basic` using command: `New-ALZEnvironment -i "terraform" -c "azuredevops" -o "c:\terraformTest" -inputs "c:\terraformConfigTest\inputs-azuredevops.yaml"`
2. Change to `hubnetworking` starter module in inputs config.
3. Deploy again using same command: `New-ALZEnvironment -i "terraform" -c "azuredevops" -o "c:\terraformTest" -inputs "c:\terraformConfigTest\inputs-azuredevops.yaml"`

I see this:
![image](https://github.com/Azure/alz-terraform-accelerator/assets/1612200/8b651902-cc84-4083-bc7b-9631246788e5)

Is it possible you changed something else like the name variables:
![image](https://github.com/Azure/alz-terraform-accelerator/assets/1612200/59db974d-3d32-46fd-95a6-eb35361a3f91)

Changing any of these would likely have the impact you saw of a full destroy and apply.

**Comment by andrew-flatters-bliss** [comment]
I followed your steps above using the `inputs-azuredevops.yaml` to make sure I didn't miss anything it asked for the additional networking variables as these wasn't in my config file which I would have expected but seems it still resulting in the module name been changed - I tried to manually change this but this made the pipelines error so I assume this is getting changed between `basic` and `hubnetworking`  not agreeing what the module is called. 

![image](https://github.com/Azure/alz-terraform-accelerator/assets/63094835/8c322666-143e-4990-a45d-411c91272bea)


I do get `Plan: 0 to add, 4 to change, 0 to destroy.` on this particular file the large amounts of destroy is when it actually runs the resulting terraform on a subscription (was trying to reproduce this but all the policies are taking a good 40 mins ish to apply. But with that module been renamed the same with my testing I would think this would result in the same)

**Comment by andrew-flatters-bliss** [comment]
Looking through the templates in this repo to see if I could spot it, looks like they should be underscored (which I think is the Terraform convention anyway) 

### basic:

https://github.com/Azure/alz-terraform-accelerator/blob/241543fc80ee3070e8c0ddf0edd1cd7ab04bcb31/templates/basic/main.tf#L1

### complete:

https://github.com/Azure/alz-terraform-accelerator/blob/241543fc80ee3070e8c0ddf0edd1cd7ab04bcb31/templates/complete/main.tf#L1

### hubnetworking:

https://github.com/Azure/alz-terraform-accelerator/blob/241543fc80ee3070e8c0ddf0edd1cd7ab04bcb31/templates/hubnetworking/main.tf#L1

**Comment by andrew-flatters-bliss** [comment]
May have also been barking up the wrong tree just was following the instructions but looking at the verified modules (which is what I intended on doing) just spotted the other template for `complete_vnext` so this may well be a bug related to the existing CAF templates. As I noticed 

`source  = "Azure/caf-enterprise-scale/azurerm"`  rather than things prefixed with the newer `avm`

**Comment by jaredfholgate** [comment]
Right, I understand the issue now. I thought it was the bootstrap run where you were seeing the replace. This is definitely not something we support, but renaming the modules to match is not a big deal, so will do that.

**Comment by jaredfholgate** [comment]
Released in v1.1.0
