### ISSUE TITLE
Feature Request: Provide Bash script instead of PowerShell

### ISSUE THREAD

**Issue by terrymandin** [Azure/alz-terraform-accelerator#116]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Customer did not want to install PowerShell.  They would prefer a Bash script.

**Describe the solution you'd like**

Please also provide a Bash option for deploying the ALZ Accelerator

**Additional context**

**Comment by GraemeMeyerGT** [comment]
I'm curious what the use case is for a Bash version of the script - PowerShell 7 is already cross-platform. I would imagine it would be pretty challenging to produce a robust version of this in Bash

**Comment by jaredfholgate** [comment]
I'm guessing the customer has a locked down image or similar and a proxy that blocks access to the PowerShell Gallery, etc. I can see the desire for an alternative in that scenario. We have considered providing a cross-platform binary alternative (i.e. C# or golang), but highly unlikely we will ever provide a bash option. Closing for now, but can re-open if demand for this increases.
