### ISSUE TITLE
bug: Set DevOps Input file bootstrap variable

### ISSUE THREAD

**Issue by terrymandin** [Azure/alz-terraform-accelerator#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bootstrap or Starter Module Deployment? (Required)

starter_module

### ALZ-PowerShell-Module Version (Required)

2.0.3

### alz-terraform-accelerator Version (Required)

0.1.9

### Starter Module (Required)

complete

### Input arguments of the ALZ-PowerShell-Module (Required)

```YAML
Change the bootstrap variable to be "alz_devops" instead of "alz_github" in the DevOps inputs file:

https://raw.githubusercontent.com/wiki/Azure/alz-terraform-accelerator/examples/powershell-inputs/inputs-azure-devops.yaml
```

### Expected Behaviour (Required)

Customer will receive the correct default value when they download the Azure DevOps inputs file.

### Actual Behaviour (Required)

Customer gets the bootstrap variable defaulted to "alz_github" in the DevOps config file.

**Comment by jaredfholgate** [comment]
Fixed, thanks for reporting @terrymandin
