### ISSUE TITLE
Feature Request: Support blob storage private networking

### ISSUE THREAD

**Issue by jaredfholgate** [Azure/alz-terraform-accelerator#14]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**

I work in a highly regulated industry and I cannot expose my blob storage endpoint publicly. Please provide a solution to make the storage account private.

**Describe the solution you'd like**

Include a private option in the quickstart. This will additionally deploy vnet, private network  self-hosted agents or runners and private dns records.

Alternatively, also support service connections for a lest complex / costly solution that provides similar protections.

The agents / runners will be vnet integrated, ensuring all state file access is private.

**Additional context**

**Comment by LaurentLesle** [comment]
@jaredfholgate  I have been working on a bootstrap environment that is deploying a vnet, vpn gw, private dns zones, vnet for self-hosted runners and then download the open vpn profile to establish a secure connection to the bootstrap machine. So any subsequent terraform deployments can target private ip addresses of the services you deploy. Let me know.

**Comment by jaredfholgate** [comment]
Released in v0.3.0
