### ISSUE TITLE
bug:   workflow_dispatch or equivalent missing from pipelines

### ISSUE THREAD

**Issue by richardf5** [Azure/alz-terraform-accelerator#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bootstrap or Starter Module Deployment? (Required)

bootstrap

### ALZ-PowerShell-Module Version (Required)

2.2.0

### alz-terraform-accelerator Version (Required)

2.2.0

### Starter Module (Required)

Complete

### Input arguments of the ALZ-PowerShell-Module (Required)

```YAML
Deploy-Accelerator -inputs .\inputsHubSpoke.yaml -autoApprove -targetDirectory .\AlzTerraformAccelerator\
```

### Expected Behaviour (Required)

GitHub Actions should have had a 'Run Workflow' button enabled.

### Actual Behaviour (Required)

No 'Run Workflow' option. This behaviour has changed since a couple of months ago.

### Steps to Reproduce (Optional)

Deploy bootstrap using input file.
Look at GitHub Actions.
See if 'Run Workflow' is available to be clicked on.

When I add "workflow_dispatch:" into the pipelines via an approved pull request, I can then see an option to run my workflow manually.

**Comment by richardf5** [comment]
I'm wondering if this is a change to the templates under bootstrap\v2.2.0\alz\github\actions\templates?

The CD template is missing the workflow_dispatch section which is in bootstrap\v2.2.0\alz\github\actions\cd.yaml

**Comment by jaredfholgate** [comment]
You should be triggering the pipeline from the main repository, not the template repository. There may have been a bug in that version that does not support the single repository version. We released a new version last night that fixed support for the single repository option.
