### ISSUE TITLE
Bug: Accelerator fails when using a personal GitHub organisation.

### ISSUE THREAD

**Issue by luke-taylor** [Azure/alz-terraform-accelerator#34]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.6.3

**azure provider**:  3.79.0

**module**: 0.0.7

### Description

**Describe the bug**

Accelerator fails when using a personal GitHub organisation.

**Steps to Reproduce**

1. Run the accelerator using GitHub as version control.

**Screenshots**

**Additional context**

**Comment by jaredfholgate** [comment]
After some research, it appears we cannot support a personal account for the accelerator due to limitations of membership. Therefore we will call this out in the documentation and close this issue for now.

**Comment by jaredfholgate** [comment]
Added a note on this in the Phase 1 docs. We cannot support this type of account.
