### ISSUE TITLE
Documentation: Detail the minimum versions for the tooling. 

### ISSUE THREAD

**Issue by luke-taylor** [Azure/alz-terraform-accelerator#35]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**

The accelerator uses terraform functions that are only available in latter versions, it would be nice to have the minimum version required to run this module. 

Also, it should be noted that Windows PowerShell will not work at installing the ALZ PS module.

**Describe the solution you'd like**

**Additional context**

**Comment by jaredfholgate** [comment]
Added specific versions.
