### ISSUE TITLE
Feature Request: Remove ambiguity for version_control_system_organization.

### ISSUE THREAD

**Issue by luke-taylor** [Azure/alz-terraform-accelerator#36]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**

It has been noted that users are erroneously placing the FQDN of their organisation here, as opposed to just the name for the case when the ADO org is not self-hosted. 

**Describe the solution you'd like**

Can we remove the ambiguity by saying version_control_system_organization_name instead, or alternatively modifying the code to allow for passing in the FQDN   

**Additional context**

**Comment by jaredfholgate** [comment]
As an FYI, it does already support passing in an FQDN (for self-hosted support):

- https://github.com/Azure/alz-terraform-accelerator/blob/6119e5a280fe93ab9b85ca305ac932f0d12fd78c/bootstrap/modules/github/locals.tf#L2
- https://github.com/Azure/alz-terraform-accelerator/blob/6119e5a280fe93ab9b85ca305ac932f0d12fd78c/bootstrap/modules/azure_devops/locals.tf#L2

Possibly the docs could be better at explaining this variable?

**Comment by luke-taylor** [comment]
Yes but am I right in saying that if you're not self-hosted, you would need to just pass in the organisation name?

**Comment by jaredfholgate** [comment]
> Yes but am I right in saying that if you're not self-hosted, you would need to just pass in the organisation name?

Yes, that is correct. The ability to add an FQDN was added later, so the docs are probably not up to scratch.

**Comment by luke-taylor** [comment]
> > Yes but am I right in saying that if you're not self-hosted, you would need to just pass in the organisation name?
> 
> Yes, that is correct. The ability to add an FQDN was added later, so the docs are probably not up to scratch.

But other than documentation, the variable itself is taking two different input types. Is it possible we can be more explicit, perhaps in the description, about the fact this needs to be the name of the org?

**Comment by jaredfholgate** [comment]
I considered adding a second variable for this, but didn't really want to add one to the UI. I can see that my instructions could be misleading:

`The organization for the version control system to use for the deployment (supply a fqdn e.g. https://vcs.company.com/my-org to use a self-hosted Azure DevOps Server)`

Perhaps something like:

`The organization for the version control system to use for the deployment. If using Azure DevOps Service supply the organisation name only (e.g. my-organisation). If using a self-hosted Azure DevOps Server supply the fqdn (e.g. https://vcs.company.com/my-organisation)`

`The organization for the version control system to use for the deployment. If using GitHub.com supply the organisation name only (e.g. my-organisation). If using a self-hosted GitHub Enterprise Server supply the fqdn (e.g. https://vcs.company.com/my-organisation)`

**Comment by jaredfholgate** [comment]
Alternative option is to supply the hostname in a separate field and default to dev.azure.com or github.com if not supplied.

**Comment by luke-taylor** [comment]
What about being able to pass both the name or the url and have a catch-all in the code? This could work right since the URLs are different from self-hosted to Azure DevOps?

**Comment by jaredfholgate** [comment]
> What about being able to pass both the name or the url and have a catch-all in the code? This could work right since the URLs are different from self-hosted to Azure DevOps?

You mean two separate variables?

**Comment by luke-taylor** [comment]
No, one variable giving the choice to pass name or url,

**Comment by jaredfholgate** [comment]
> No, one variable giving the choice to pass name or url,

Ok, it already does this, but perhaps the variable name and description needs to be updated to make it more obvious.

**Comment by jaredfholgate** [comment]
Variable names updated.
