### ISSUE TITLE
Bug: Accelerator fails if Azure DevOps extension is not already installed. 

### ISSUE THREAD

**Issue by luke-taylor** [Azure/alz-terraform-accelerator#37]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.6.3

**azure provider**: 3.79.0

**module**: 0.0.7

### Description

**Describe the bug**

The Azure DevOps implementation makes use of an Azure DevOps extension in the pipelines in order to install and run terraform. This installation isn't handled by the accelerator so will cause a break upon first run. 

Perhaps this can be resolved by either:
1. Removing the dependency on the extension. 
2. Installing the extension as part of the bootstrap.

**Steps to Reproduce**

1. Create a new Azure DevOps Organisation.
3. Run the Accelerator with Azure DevOps
4. Go to run the CD Pipeline. 

**Screenshots**

**Additional context**

**Comment by jaredfholgate** [comment]
Yes, I realised this was the case, but totally forgot to come back to it. 

It looks like there is an API for it, but not supported by the Terraform provider: https://learn.microsoft.com/en-us/rest/api/azure/devops/extensionmanagement/installed-extensions/install-extension-by-name?view=azure-devops-rest-7.0&tabs=HTTP

I think in the short term the best thing to do is add it to the quick start guide. I appreciate we could use the az cli step instead, but prefer to use the DevLabs abstraction.

Then add another feature to do one of the following:

- Add it to the Terraform provider, the update the accelerator
- Add a provisioner to the accelerator

**Comment by jaredfholgate** [comment]
Consider this option also: https://learn.microsoft.com/en-us/azure/devops/marketplace/install-extension?view=azure-devops&tabs=azure-devops-cli#install-an-extension

**Comment by luke-taylor** [comment]
Do we document a command to be run before? 

Is it possible to create our own abstraction, instead of using an extension?

**Comment by luke-taylor** [comment]
Do we document a command to be run before? 

Is it possible to create our own abstraction, instead of using an extension?

**Comment by jaredfholgate** [comment]
Three options:

1. Document the dependency on the task.
2. Automate the installation of the task.
3. Remove the dependency on the task.

I am leaning towards option 2 until such time as Terraform becomes a built in task (possibly mid-2024). It may make the code a bit less readable, but will avoid an extra step and any security process required to install the task for end users.

**Comment by luke-taylor** [comment]
Can 2. be done within the Terraform code as a provisioner? Then we can remove it once it's been made built-in.

Other than that, since we're making our own templates to an extent, i.e. apply.yml, plan.yml, they are the abstraction so we could have the logic within those to do the terraform apply, plan etc.

**Comment by jaredfholgate** [comment]
> Can 2. be done within the Terraform code as a provisioner? Then we can remove it once it's been made built-in.
> 
> Other than that, since we're making our own templates to an extent, i.e. apply.yml, plan.yml, they are the abstraction so we could have the logic within those to do the terraform apply, plan etc.

I think the biggest issue with option 3 is actually the installer now I have taken a look. I think we can add Terraform to the self-hosted agent image and it appears to be on Ubuntu latest. The init / plan / apply code is not that big a deal. That would cover the current options. I'm just thinking ahead to a scenario where we need to support some unknown agent and have to install Terraform in the pipeline. The code in the task handles a lot of scenarios, such as different OS, Architecture and proxies.

**Comment by jaredfholgate** [comment]
And yes, option 2 could be done with a provisioner and may be the best option right now to avoid any complications around whether Terraform is actually installed on the agent.

**Comment by jaredfholgate** [comment]
The provisioner has now been removed and we broke the dependency on the DevLabs task.
