### ISSUE TITLE
Bug: Accelerator for Azure DevOps, Workload Federated Identity, fails without submitting parallelism request.

### ISSUE THREAD

**Issue by luke-taylor** [Azure/alz-terraform-accelerator#38]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.6.3

**azure provider**: 3.79.0

**module**: 0.0.7

### Description

**Describe the bug**

Every organisation will require the user to fill out an Azure DevOps Parallelism Request in order to use Microsoft Hosted Agents with pipelines, without this the pipelines won't run. Currently the accelerator doesn't cater to this. 

We could fix this by:
1. Documenting the form as prerequisite. 

**Steps to Reproduce**

1. Create a new Azure DevOps organisation 
3. Run Accelerator with Azure DevOps, choosing WorkloadFederatedIdentity 
4. Run pipeline.

**Screenshots**

**Additional context**

**Comment by jaredfholgate** [comment]
I thought every organisation gets 1 parallel pipeline by default? Are there some cases where that does not happen? Do you have the error message, so I can dig a bit deeper?

**Comment by luke-taylor** [comment]
I'll try dig it out, though it wasn't my error. I've had this multiple times on customer engagements so I always requested the customer complete the form before engaging.

**Comment by jaredfholgate** [comment]
> I'll try dig it out, though it wasn't my error. I've had this multiple times on customer engagements so I always requested the customer complete the form before engaging.

Oh, interesting I wasn't aware of this. I have always had at least one Microsoft agent when creating an org. Wonder if it is something that has changed.

**Comment by luke-taylor** [comment]
<img width="830" alt="image" src="https://github.com/Azure/alz-terraform-accelerator/assets/77284962/2a356890-34cf-480b-b3de-3b626a2e1d81">

**Comment by jaredfholgate** [comment]
They must have changed it, as my older orgs have it by default and a new one I setup does not. Here is the FAQ: 
![image](https://github.com/Azure/alz-terraform-accelerator/assets/1612200/b054c18e-1bd1-4077-a6f0-ad5a5b30d4be)

https://learn.microsoft.com/en-us/azure/devops/organizations/billing/billing-faq?view=azure-devops&tabs=new-nav#q--can-i-use-azure-devops-for-free-

**Comment by jaredfholgate** [comment]
I think we'll need to add this to the docs in that case.

**Comment by jaredfholgate** [comment]
More info: https://learn.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&tabs=ms-hosted#how-much-do-parallel-jobs-cost

"When you create a new Azure DevOps organization, you may not always be given this free grant by default."

**Comment by luke-taylor** [comment]
Could we also have an explicit choice whether or not to use microsoft-hosted or self-hosted instead of it being hidden in the method of authentication? Because you can still use Federated Workload Identity with a self-hosted agent. 

I suspect folks wanting to get going as fast as possible wouldn't want to wait 1-2 days in order to get this running.

**Comment by luke-taylor** [comment]
> More info: https://learn.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&tabs=ms-hosted#how-much-do-parallel-jobs-cost
> 
> "When you create a new Azure DevOps organization, you may not always be given this free grant by default."

Gotta love the ambiguity!

**Comment by jaredfholgate** [comment]
> Could we also have an explicit choice whether or not to use microsoft-hosted or self-hosted instead of it being hidden in the method of authentication? Because you can still use Federated Workload Identity with a self-hosted agent.
> 
> I suspect folks wanting to get going as fast as possible wouldn't want to wait 1-2 days in order to get this running.

Good point, was planning to add that option as part of this feature anyway: https://github.com/Azure/alz-terraform-accelerator/issues/14

**Comment by jaredfholgate** [comment]
Updated docs in v0.3.0. Also defaulted to self-hosted agents, which do not require this pre-requisite.
