### ISSUE TITLE
Bug: Require additional Root Management Group permissions 

### ISSUE THREAD

**Issue by terrymandin** [Azure/alz-terraform-accelerator#44]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: hashicorp/setup-terraform@v2

**azure provider**:
- registry.terraform.io/Azure/caf-enterprise-scale/azurerm 4.2.0
- Finding hashicorp/time versions matching ">= 0.7.0"...
- Finding hashicorp/random versions matching ">= 3.1.0"...
- Finding azure/azapi versions matching ">= 1.3.0"...
- Finding hashicorp/azurerm versions matching ">= 3.0.0, >= 3.54.0"...
- Installing hashicorp/time v0.9.1...
- Installed hashicorp/time v0.9.1 (signed by HashiCorp)
- Installing hashicorp/random v3.5.1...
- Installed hashicorp/random v3.5.1 (signed by HashiCorp)
- Installing azure/azapi v1.10.0...
- Installed azure/azapi v1.10.0 (signed by a HashiCorp partner, key ID 6F0B91BDE98478CF)
- Installing hashicorp/azurerm v3.81.0...
- Installed hashicorp/azurerm v3.81.0 (signed by HashiCorp)

**module**: 0.0.7

### Description

**Describe the bug**

Received the permission error below when deploying to GitHub.
```
│ Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '265b04b7-8db1-49e1-849a-688a74515809' with object id '265b04b7-8db1-49e1-849a-688a74515809' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/write' over scope '/providers/Microsoft.Management/managementGroups/3a54772d-fb8a-4d83-888a-fc2073fdfed7/providers/Microsoft.Authorization/roleAssignments/8cef976a-171f-c052-300b-bdd870297836' or the scope is invalid. If access was recently granted, please refresh your credentials."
		│
		│   with module.azure.azurerm_role_assignment.alz["plan_management_group"],
		│   on ..\modules\azure\managed_identity.tf line 51, in resource "azurerm_role_assignment" "alz":
│   51: resource "azurerm_role_assignment" "alz" {
```

**Steps to Reproduce**

1. Follow Phase 1 steps for GitHub.  Assign "Management Group Contributor" to SPN.
![image](https://github.com/Azure/alz-terraform-accelerator/assets/833055/790a5768-2cc8-4337-862b-1a2d45a6ebab)
1. Follow Phase 2 2.2.2 steps. 
1. Fails on step 8 with error above.
1. Giving SPN Owner permission on the root management group allowed me to continue

**Screenshots**

**Additional context**

**Comment by jaredfholgate** [comment]
Thanks for reporting, will follow up on this.

**Comment by jaredfholgate** [comment]
@terrymandin Good spot, somehow managed to overlook this during testing. My testing accounts must already have owner access rights. Will update the docs accordingly.

**Comment by jaredfholgate** [comment]
Resolved and published.

**Comment by terrymandin** [comment]
Awesome, thanks Jared!

**Comment by terrymandin** [comment]
Just tested, and additional permissions were not required.  Thank you for the fix @jaredfholgate
