### ISSUE TITLE
Bug: Changes must be made through a pull request.

### ISSUE THREAD

**Issue by terrymandin** [Azure/alz-terraform-accelerator#45]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: hashicorp/setup-terraform@v2

**azure provider**:
- registry.terraform.io/Azure/caf-enterprise-scale/azurerm 4.2.0
- Finding hashicorp/time versions matching ">= 0.7.0"...
- Finding hashicorp/random versions matching ">= 3.1.0"...
- Finding azure/azapi versions matching ">= 1.3.0"...
- Finding hashicorp/azurerm versions matching ">= 3.0.0, >= 3.54.0"...
- Installing hashicorp/time v0.9.1...
- Installed hashicorp/time v0.9.1 (signed by HashiCorp)
- Installing hashicorp/random v3.5.1...
- Installed hashicorp/random v3.5.1 (signed by HashiCorp)
- Installing azure/azapi v1.10.0...
- Installed azure/azapi v1.10.0 (signed by a HashiCorp partner, key ID 6F0B91BDE98478CF)
- Installing hashicorp/azurerm v3.81.0...
- Installed hashicorp/azurerm v3.81.0 (signed by HashiCorp)

**module**: 0.0.7

### Description

**Describe the bug**

GitHub repo is being created with branch permissions that require changes to be made through a pull request which causes the GitHub deployment to fail.

**Steps to Reproduce**

1. Follow Phase 1 for GitHub.
2. Deploy Phase 2 2.2.2
3. Deployment fails with a "Changes must be made through a pull request" in Step 8.
4. Go into the repo in GitHub and uncheck "Require a pull request before merging"
5. Run through steps in Phase 2 2.2.2
6. Deployment succeeds.

**Screenshots**

![image](https://github.com/Azure/alz-terraform-accelerator/assets/833055/ed4e74c8-b59f-45ae-a212-2988e9984ba3)
![image](https://github.com/Azure/alz-terraform-accelerator/assets/833055/ff306b2f-34e7-4201-a956-ea2e5b0d8c44)

**Additional context**

**Comment by jaredfholgate** [comment]
@terrymandin Are you able to confirm this occurs on the first apply of the accelerator? There is a dependency on the files being created to ensure the branch policy is not created until the files have. I would expect to see this issue on a subsequent run of the accelerator, but the accelerator is designed to be a single-run fire and forget at this stage.

If you are trying to run an update, then you would need to remove the branch protection as you have done. It is something we could add to the docs, but keen to understand your process and use case. Thanks

**Comment by terrymandin** [comment]
I just re-ran the

**Comment by terrymandin** [comment]
I just re-ran and confirmed that it does NOT require the pull request on the first run.
