### ISSUE TITLE
Bug: Updates to Terraform result in Permission Error on Deployment

### ISSUE THREAD

**Issue by terrymandin** [Azure/alz-terraform-accelerator#46]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: hashicorp/setup-terraform@v2

**azure provider**:
- registry.terraform.io/Azure/caf-enterprise-scale/azurerm 4.2.0
- Finding hashicorp/time versions matching ">= 0.7.0"...
- Finding hashicorp/random versions matching ">= 3.1.0"...
- Finding azure/azapi versions matching ">= 1.3.0"...
- Finding hashicorp/azurerm versions matching ">= 3.0.0, >= 3.54.0"...
- Installing hashicorp/time v0.9.1...
- Installed hashicorp/time v0.9.1 (signed by HashiCorp)
- Installing hashicorp/random v3.5.1...
- Installed hashicorp/random v3.5.1 (signed by HashiCorp)
- Installing azure/azapi v1.10.0...
- Installed azure/azapi v1.10.0 (signed by a HashiCorp partner, key ID 6F0B91BDE98478CF)
- Installing hashicorp/azurerm v3.81.0...
- Installed hashicorp/azurerm v3.81.0 (signed by HashiCorp)

**module**: 0.0.7

### Description

**Describe the bug**

I made a change to the Terraform to add a subscription to the Corp management group.  Received the message below even though my SPN has Owner privs on the subscription.

```
│ Error: [DEBUG] Error assigning Subscription ID "3776c7b9-3885-492f-8f00-fe941a916986" to Management Group "abc-corp": managementgroups.SubscriptionsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Permission to write and delete on resources of type 'Microsoft.Authorization/roleAssignments' is required on the subscription or its ancestors." Details=[{"raw":"Subscription ID: '/subscriptions/<sub id>'"}]
```

**Steps to Reproduce**

1. Follow phases 1, 2, and 3 for GitHub
2. Assign Owner permission to SPN in the landing zone subscription.
3. Update main.tf with the following:
```
  subscription_id_overrides = {
    corp = [ var.subscription_id_corp_landing_zone ]
  }
```
variables.tf:
```
variable "subscription_id_corp_landing_zone" {
  description = "The identifier of the Corporate Landing Zone Subscription. (e.g '00000000-0000-0000-0000-000000000000')|5|azure_subscription_id"
  type        = string
}
```
terraform.tfvars:
```
subscription_id_corp_landing_zone = "<sub id>"
```
4. Commit and push to GitHub
5. Get Error above 

**Screenshots**

**Additional context**

**Comment by jaredfholgate** [comment]
Hi @terrymandin. If you are updating the subscription ID's post the bootstrap, you would need to grant to permission to the user assigned managed identities (uami) that the bootstrap creates. The `plan` uami would need `Reader` and the `apply` uami would need `Owner`. 

Please let me know if I am overlooking something.

**Comment by terrymandin** [comment]
Hi @jaredfholgate , I will give this a try.  I think it will be quite common to add additional subscriptions to Corp and Online as the customer adopts their new LZ.  I suggest we add a section in the documentation that describes the permissions required for updates.

**Comment by terrymandin** [comment]
@jaredfholgate, I tested updating the permissions and was able to add the subscription to the Corp management group.  Thank you for your assistance.
