### ISSUE TITLE
Bug: Add call to Az-LoginAccount

### ISSUE THREAD

**Issue by terrymandin** [Azure/alz-terraform-accelerator#58]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:
1.6.3

**azure provider**:
- Using previously-installed hashicorp/azurerm v3.82.0
- Using previously-installed azure/azapi v1.10.0
- Using previously-installed microsoft/azuredevops v0.10.0
- Using previously-installed hashicorp/random v3.5.1

**module**:

### Description

**Describe the bug**

I received an error at step 8 in 2.2.1 as I was not logged into the correct account.  Recommend adding a call to Az-LoginAccount at the step 1 of 2.2.1.

**Steps to Reproduce**

1. Login to an account using Az-LoginAccount
2. Choose subscription id's from a different account
3. At step 8 in 2.2.1 you will receive an error

**Screenshots**

**Additional context**

**Comment by jaredfholgate** [comment]
Step [1.3.1](https://github.com/Azure/alz-terraform-accelerator/wiki/%5BUser-Guide%5D-Quick-Start-Phase-1#131-authenticate-via-user-account) is where you authenticate. This should be done prior to step 2.2.1. 

The PowerShell module does not query Azure, only the Terraform apply step reaches out to Azure.

Perhaps if you can share the error message we can pinpoint the issue.

**Comment by terrymandin** [comment]
Ah, you are correct.  Missed that. Closing now
