### ISSUE TITLE
Bug Report resource type "terraform_data" is not supported by provider "terraform.io/builtin/terraform"

### ISSUE THREAD

**Issue by ronaldbok** [Azure/alz-terraform-accelerator#61]
Hello,

Last week i started to use this project. I ran the command 'New-ALZEnvironment -Cicd azuredevops -iac terraform'

It worked fine till i got the message that a resource name was to long.
Stupid my fault. i gave a to long name for the value default resource names (my be modify the script to use only the first 4 digits)

So Today i cleaned everything up, and started again. All the values enter in the script are the same as last week only the value 'default resource names' Was shortend to 4 characters.

But now i get the following error

"
Error: Invalid resource type
│
│ on ../modules/azure_devops/extension.tf line 1, in resource "terraform_data" "dev_labs_extension":
│ 1: resource "terraform_data" "dev_labs_extension" {
│
│ The provider terraform.io/builtin/terraform does not support resource type "terraform_data".
╵
╷
│ Error: Invalid resource type
│
│ on ../modules/azure_devops/extension.tf line 10, in resource "terraform_data" "dev_labs_extension":
│ 10: command = "${path.module}/extension-install.ps1 -patToken "${self.input.pat_token}" -organizationName "${self.input.organization_name}""
│
│ A managed resource type "terraform_data" is not supported by provider "terraform.io/builtin/terraform".
╵
╷
│ Error: Invalid resource type
│
│ on ../modules/azure_devops/extension.tf line 10, in resource "terraform_data" "dev_labs_extension":
│ 10: command = "${path.module}/extension-install.ps1 -patToken "${self.input.pat_token}" -organizationName "${self.input.organization_name}""
│
│ A managed resource type "terraform_data" is not supported by provider "terraform.io/builtin/terraform".
"

Can someone help me please ?

Greetings Ronald

**Comment by matt-FFFFFF** [comment]
You need Terraform 1.6 to use that resource. What version are you using?

**Comment by ronaldbok** [comment]
Hello Matt,

First of all thank you for the great project. Our Company was trying different version of the terraform landingzone but on all version we hit a brick wall. Then we found your Video at the presentation on HashiConf.

So last week I start trying this. All went well but I gave one of the variables the wrong value so a resources ended up with a name that was to long.

Yesterday I started again. That was where I got the error code.

Now answering your Question, The Terraform Version I was using was the version included in the Bash Cloud shell (Version 1.3.2). Last week this was working fine.
So I updated the terraform version to the lastest version using the instructions from Microsoft (Configure Terraform in Azure Cloud Shell with Bash | Microsoft Learn<https://learn.microsoft.com/en-us/azure/developer/terraform/get-started-cloud-shell-bash?tabs=bash>)

And started again.

Know it is working. Thanks.

Greetings Ronald





Met vriendelijke groet,
Ronald Bok
Technical Consultant

[cid:LogoPayOff_afa158b2-4d87-4534-b72c-3d23432a2134.png]


T       +31 6 1260 2190<tel:%20+31%206%201260%202190>
M       ***@***.******@***.***>
W       www.nexxt.one<http://www.nexxt.one>

DISCLAIMER Dit e-mailbericht is vertrouwelijk en persoonlijk. Indien dit bericht niet voor jou bestemd is, verzoeken wij je dit onmiddellijk aan de afzender te melden en het bericht te verwijderen. Je mag dit bericht en/of bijlage(n) niet verder verspreiden. NEXXT controleert al haar uitgaande e-mailberichten op aanwezigheid van virussen. NEXXT is niet aansprakelijk voor en/of in verband met alle mogelijke gevolgen en/of schade voortvloeiend uit dit e-mailbericht, zoals schade door virussen.

From: Matt White ***@***.***>
Sent: Monday, 4 December 2023 19:24
To: Azure/alz-terraform-accelerator ***@***.***>
Cc: Ronald Bok ***@***.***>; Author ***@***.***>
Subject: [Extern]Re: [Azure/alz-terraform-accelerator] Bug Report resource type "terraform_data" is not supported by provider "terraform.io/builtin/terraform" (Issue #61)


You need Terraform 1.6 to use that resource. What version are you using?

**Comment by jaredfholgate** [comment]
Thanks for the feedback here. We need to add a check and docs for this. The provisioner is a work around and looking for a way to remove it ASAP. It is just there to ensure the DevLabs Terraform Task is installed in Azure DevOps, we ideally want to break that dependency, but the installer part is hard to replicate.

**Comment by matt-FFFFFF** [comment]
Glad you like it @ronaldbok!

I can't take credit for the work, that must go to @luke-taylor and @jaredfholgate

**Comment by jaredfholgate** [comment]
The provisioner has now been removed and we broke the dependency on the DevLabs task.
