### ISSUE TITLE
Feature Request: Guidance for Customers not using Azure DevOps or GitHub

### ISSUE THREAD

**Issue by terrymandin** [Azure/alz-terraform-accelerator#69]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Some customers do not use Azure DevOps or GitHub.  Currently we have a [zip file in the IP Kit](https://microsoft.sharepoint.com/teams/ASDIPRelease/IP%20Release/Forms/AllItems.aspx?ga=1&id=%2Fteams%2FASDIPRelease%2FIP%20Release%2FSecure%20Infrastructure%2FVBD%2FAzure%20landing%20zone%20Value%20Based%20Deliveries%2F4%2E%20ALZ%20Support%20Content%2F9%2E%20ALZ%20Terrraform&viewid=971b6985%2D5ac6%2D47e5%2Da6dc%2D5c0664b149a9) that can be downloaded and sent to the customer.  However, this leads to two code bases and the possibility that they can become out of sync.  Could we provide guidance on how we can use the accelerator code base for these customers.

**Describe the solution you'd like**

Prescriptive guidance on how a CSA could use the accelerator code base for customers who do not use Azure DevOps or GitHub.

**Additional context**

**Comment by terrymandin** [comment]
If we could run something like this:
 
New-ALZEnvironment -IaC "terraform" -Cicd "none"
 
and have the script output the Terraform files to the current directory I think that would work.  It would allow us to retire a parallel code stream we have currently stored in a zip file in SharePoint.  This would ensure the customers without GitHub or DevOps  will always have the latest code fixes.

**Comment by jaredfholgate** [comment]
`local` option added to output the files to the local file system.
