### ISSUE TITLE
Bug: AuthorizationFailed - Devops/complete

### ISSUE THREAD

**Issue by terrymandin** [Azure/alz-terraform-accelerator#72]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

azure-cli                         2.55.0
core                              2.55.0
telemetry                          1.1.0
Extensions:
azure-devops                      0.26.0
Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

- Installing hashicorp/random v3.6.0...
- Installed hashicorp/random v3.6.0 (signed by HashiCorp)
- Installing azure/azapi v1.11.0...
- Installed azure/azapi v1.11.0 (signed by a HashiCorp partner, key ID 6F0B91BDE98478CF)
- Installing hashicorp/azurerm v3.85.0...
- Installed hashicorp/azurerm v3.85.0 (signed by HashiCorp)
- Installing hashicorp/time v0.10.0...
- Installed hashicorp/time v0.10.0 (signed by HashiCorp)

### Description

**Describe the bug**

Receiving an AuthorizationFailed message when running the TF Apply.  Note that the resource group in the scope ```/subscriptions/68b9adfe-20bc-47c6-b0ce-0f81549a484c/resourcegroups/rg-management``` does not exist.  See attached for full logs.

```
│ Error: checking for presence of existing resource group: resources.GroupsClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '14a812a4-000e-4279-afa9-a48158176478' with object id '14a812a4-000e-4279-afa9-a48158176478' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/68b9adfe-20bc-47c6-b0ce-0f81549a484c/resourcegroups/rg-management' or the scope is invalid. If access was recently granted, please refresh your credentials."

```

[PowerShell.txt](https://github.com/Azure/alz-terraform-accelerator/files/13835813/PowerShell.txt)
[TerraformPlanLog.txt](https://github.com/Azure/alz-terraform-accelerator/files/13835815/TerraformPlanLog.txt)

**Steps to Reproduce**

1. Do Phase 1 and 2 for DevOps
2. Fails when I run the pipeline

**Screenshots**

Error
<img width="923" alt="image" src="https://github.com/Azure/alz-terraform-accelerator/assets/833055/ae659b12-2859-4a8c-8ccd-4d2bf99b8673">

Resource Groups
<img width="715" alt="image" src="https://github.com/Azure/alz-terraform-accelerator/assets/833055/d93eaa72-6161-42b2-aeae-595f89c15a43">

Management Subscription
<img width="539" alt="image" src="https://github.com/Azure/alz-terraform-accelerator/assets/833055/b65c0dcf-753e-4880-8106-f5853f80d758">

RBAC
<img width="883" alt="image" src="https://github.com/Azure/alz-terraform-accelerator/assets/833055/df92a6bc-293f-4bd0-9348-7c4e6c9bc7ea">

**Additional context**

**Comment by luke-taylor** [comment]
@terrymandin Looks like the role assignments for the subscription ids were not getting applied, the fix has been implemented in #73.
