### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ronaldbok** [Azure/alz-terraform-accelerator#78]
During the Deployment of the Connectivity Subscription there is a default Firewall installed.

I Would be helpful if there is a option to choose witch firewall will be installed. 

A Lot of our customers using the Fortigate or Watchguard firewall

**Comment by jaredfholgate** [comment]
Hi @ronaldbok. Can you provide a bit more context on your request? Is this specific to the accelerator or would this issue sit better on the https://github.com/Azure/terraform-azurerm-caf-enterprise-scale repo?
