### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ronaldbok** [Azure/alz-terraform-accelerator#79]
Hello

After de default deployment only the Network for the connectivity Subscription is build.

What about the networks and routing in the Identity subscription (for the deployment of the Bastion and Azure ARC) and the Management subscription (for the deployment of DC and SyncServers)

It would be very helpful if all vnets and other network components would be deployed to all subscriptions.

**Comment by jaredfholgate** [comment]
Hi @ronaldbok. Can you provide more context please? Which starter module are you using? Would this sit better with the module itself? https://github.com/Azure/terraform-azurerm-caf-enterprise-scale

**Comment by ronaldbok** [comment]
Hello Jared,

Sorry  i was not clear. 

We deployed the ALZ met the hubnetworking deployment.

We need a working network in all Landingzones.

We are looking for a Solution to implement for our customers to deploy the Enterprise scale Landing zone.
The solution must include all basic settings in the subscriptions so that we can deploy the same ALZ to all of our customers.

Your solution is the first one that Realy works, so we like to help get it better.
At this moment we are working on the solution 4 people. If the Basic ALZ is ready for our needs we want to go to the next step and deploy the landingzones for the Applications.

Maybe it is easier to communicate true email or teams my adres is ronald.bok@nexxt.one

Hope to hear from you

Greetings Ronald

**Comment by luke-taylor** [comment]
Hey @ronaldbok, 

We actually have issue with this to accelerate the `lz-vending` module here #2, this will then allow you to vend landing zones for your applications through a secure CI/CD process just like the ALZ is done today. 

The features of that module can be found here https://github.com/Azure/terraform-azurerm-lz-vending 

I hope this answers your question!
