### ISSUE TITLE
Feature Request: `complete` module config updates

### ISSUE THREAD

**Issue by jaredfholgate** [Azure/alz-terraform-accelerator#85]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**

It is an improvement to the `complete` module config to make it easier to use.

**Describe the solution you'd like**

1. Add the templating as used in the `complete_vnext` module to avoid repetition.
2. Add a complete example that users can copy and paste and know how the complex objects are formed.

N/A

**Additional context**

**Comment by ronaldbok** [comment]
👍

**Comment by jaredfholgate** [comment]
Templating added in v0.4.0. Complete sample still pending.

**Comment by jaredfholgate** [comment]
Closing for now as we have a number of examples available.
