### ISSUE TITLE
Feature Request: Add VBD config.yaml files to repo

### ISSUE THREAD

**Issue by terrymandin** [Azure/alz-terraform-accelerator#91]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**

The current ALZ Deployment VBD has many more variables than are available in the current config.yaml file.  When deploying the field would all have to create the additional variables in the config.yaml.

**Describe the solution you'd like**

I have attached more extensive config.yaml files that correspond to the current VBD deliverables for hub and spoke and vWan deployments.  Please add these to the accelerator repo.  Note that I added the ".txt" extension to them so I could add them to this feature request.

[config-hub-spoke.yaml.txt](https://github.com/Azure/alz-terraform-accelerator/files/13954105/config-hub-spoke.yaml.txt)
[config-vwan.yaml.txt](https://github.com/Azure/alz-terraform-accelerator/files/13954106/config-vwan.yaml.txt)

**Comment by jaredfholgate** [comment]
Released in v0.4.1
