### ISSUE TITLE
Feature Request: Add input sample files

### ISSUE THREAD

**Issue by terrymandin** [Azure/alz-terraform-accelerator#92]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**

When working with customers I would prefer to work with an "inputs" file instead of using the PowerShell prompts.  This will give me the following benefits:
1. Ability to enter the inputs out of order
2. Ability to save the file as an artifact of the delivery
3. Ability to create the file across multiple sessions and desktops.
4. Ability to re-run the file if necessary.  (This can also be accomplished using the cache)

Also note, that "organization" is spelled with an "s" (e.g. "organisation") in some places.  This should be corrected.

**Describe the solution you'd like**

I have attached a couple sample inputs files, one for GitHub and one for Azure DevOps.  Note I have appended ".txt" so they can be included in this feature request.  It would be great if they were included in the repo.  I will reference them from the ALZ VBD.

[inputs-devops.yaml.txt](https://github.com/Azure/alz-terraform-accelerator/files/13955754/inputs-devops.yaml.txt)
[inputs-github.yaml.txt](https://github.com/Azure/alz-terraform-accelerator/files/13955755/inputs-github.yaml.txt)

**Additional context**

**Comment by jaredfholgate** [comment]
Released in v0.4.1
