### ISSUE TITLE
Feature Request: Obsolete Terraform module reference

### ISSUE THREAD

**Issue by tonyskidmore** [Azure/alz-terraform-accelerator#96]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**

The [Starter Module HubNetworking](https://github.com/Azure/alz-terraform-accelerator/wiki/%5BUser-Guide%5D-Starter-Module-HubNetworking) in the user guide uses the [terraform-azurerm-vnet-gateway](https://github.com/Azure/terraform-azurerm-vnet-gateway) Terraform module, but this been marked as [This repository is obsolete](https://github.com/Azure/terraform-azurerm-vnet-gateway/commit/23f12811d8fb7aa5a0c24dfcb527639c2bc2e513) by the maintainers in favour of [terraform-azurerm-avm-ptn-vnetgateway](https://github.com/Azure/terraform-azurerm-avm-ptn-vnetgateway).

**Describe the solution you'd like**

The accelerator not to reference unmaintained Terraform modules.

**Additional context**

**Comment by tonyskidmore** [comment]
I subsequently discovered #94 - I didn't find an existing issue, but this can be closed when that PR is merged.

**Comment by luke-taylor** [comment]
Closing this, new module references have been added.
